name: Build And Upload
on:
  push:
    tags:
      - "*"
jobs:
  call-reusable-workflow:
    uses: intisy/workflows/.github/workflows/build.yml@main
    with:
      ref_name: ${{ github.ref_name }}
    secrets:
      envPAT: ${{ secrets.PAT }}